#!/bin/bash

#find . -iname "*.cpp" -print0 | xargs -0 dos2unix
#find . -iname "*.h" -print0 | xargs -0 dos2unix
#find . -iname "*.hpp" -print0 | xargs -0 dos2unix
#find . -iname "*.txt" -print0 | xargs -0 dos2unix
#find . -iname "*.m" -print0 | xargs -0 dos2unix
#find . -iname "*.mm" -print0 | xargs -0 dos2unix
#find . -iname "README.md" -print0 | xargs -0 dos2unix
#find . -iname "*.xml" -print0 | xargs -0 dos2unix
#find . -iname "*.pri" -print0 | xargs -0 dos2unix
#find . -iname "*.pro" -print0 | xargs -0 dos2unix
#find . -iname "*.rc" -print0 | xargs -0 dos2unix
#find . -iname "*.css" -print0 | xargs -0 dos2unix
#find . -iname "*.conf" -print0 | xargs -0 dos2unix
#find . -iname "*.ui" -print0 | xargs -0 dos2unix
#find . -iname "*.qrc" -print0 | xargs -0 dos2unix
#find . -iname "*.bat" -print0 | xargs -0 dos2unix
#find . -iname "*.sh" -print0 | xargs -0 dos2unix
#find . -iname "*.ts" -print0 | xargs -0 dos2unix
#find . -iname "*.qss" -print0 | xargs -0 dos2unix
find . -iname "*.*" -print0 | xargs -0 dos2unix
